### ISSUE TITLE
'All' distribution?

### ISSUE THREAD

**Issue by BitBuf** [PorkLib/PorkLib#50]
Distribute a jar with all library components in, it's a bit weirdy having to put the binary library in my Gradle and being granted access to like 7 other ones. Things like this are all over the place when including PorkLib, imo an 'all' dist will help clear this stuff up.

**Comment by Crystallinqq** [comment]
dont think i asked

**Comment by DaMatrix** [comment]
Sub-dependencies aren't really anything out of the ordinary, all sorts of other things do that.

![example 1](https://i.daporkchop.net/D7Z5QiH6.png)
![example 2](https://i.daporkchop.net/Ffv5kyhD.png)

You can add `net.daporkchop.lib:full` as a dependency, [it depends on every other module](https://github.com/PorkStudios/PorkLib/blob/development/build.gradle#L151-L157).

**Comment by BitBuf** [comment]
damn, i am quite the spesh
