### ISSUE TITLE
Make sublibraries available individually

### ISSUE THREAD

**Issue by willemml** [PorkLib/PorkLib#52]
It would be very useful to not be required to include the entirety of PorkLib in a project when I only need one part of it.

**Comment by DaMatrix** [comment]
Which modules are you trying to use? You certainly don't need to include everything...

**Comment by willemml** [comment]
The one i am after is the minecraft chat parsing library.

**Comment by DaMatrix** [comment]
group ID is `net.daporkchop.lib`, artifact ID is `minecraft-text`.

**Comment by willemml** [comment]
And this wont include anything other than logging and common?

**Comment by DaMatrix** [comment]
logging depends on binary and common, binary depends on common, common depends on unsafe.

Other than that, nope!

**Comment by willemml** [comment]
Oh ok, awesome, thanks, also the website is down by the way, but thanks for letting me know about this, because that saves me lots of time.

**Comment by DaMatrix** [comment]
You can see a list of all the available modules here: https://maven.daporkchop.net/net/daporkchop/lib/ . I should really start writing some docs at some point...

**Comment by willemml** [comment]
Yeah, although just giving a brief sentence about the contents of this issue in the README would probably be enough for almost anyone to get started while there are no docs (also linking the maven repo).
